// search wocmen constants;
export const SEARCH_WOCMEN_PENDING = "SEARCH_WOCMEN_PENDING";
export const SEARCH_WOCMEN_SUCCESS = "SEARCH_WOCMEN_SUCCESS";
export const SEARCH_WOCMEN_FAIL = "SEARCH_WOCMEN_FAIL";
export const CLEAR_SEARCH_TOAST = "CLEAR_SEARCH_TOAST ";


// newsletter
export const NEWSLETTER_PENDING = "NEWSLETTER_PENDING";
export const NEWSLETTER_SUCCESS = "NEWSLETTER_SUCCESS";
export const NEWSLETTER_FAIL = "NEWSLETTER_FAIL";
export const CLEAR_NEWSLETTER_TOAST = "CLEAR_NEWSLETTER_TOAST ";

// contact us
export const CONTACT_PENDING = "CONTACT_PENDING";
export const CONTACT_SUCCESS = "CONTACT_SUCCESS";
export const CONTACT_FAIL = "CONTACT_FAIL";
export const CLEAR_CONTACT_TOAST = "CLEAR_CONTACT_TOAST ";