// search wocmen constants;
export const SEARCH_WOCMEN_PENDING = "SEARCH_WOCMEN_PENDING";
export const SEARCH_WOCMEN_SUCCESS = "SEARCH_WOCMEN_SUCCESS";
export const SEARCH_WOCMEN_FAIL = "SEARCH_WOCMEN_FAIL";
export const CLEAR_SEARCH_TOAST = "CLEAR_SEARCH_TOAST ";


// newsletter
export const NEWSLETTER_PENDING = "NEWSLETTER_PENDING";
export const NEWSLETTER_SUCCESS = "NEWSLETTER_SUCCESS";
export const NEWSLETTER_FAIL = "NEWSLETTER_FAIL";
export const CLEAR_NEWSLETTER_TOAST = "CLEAR_NEWSLETTER_TOAST ";

// contact us
export const CONTACT_PENDING = "CONTACT_PENDING";
export const CONTACT_SUCCESS = "CONTACT_SUCCESS";
export const CONTACT_FAIL = "CONTACT_FAIL";
export const CLEAR_CONTACT_TOAST = "CLEAR_CONTACT_TOAST ";

// sign up
export const REGISTER_PENDING = "REGISTER_PENDING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const CLEAR_REGISTER_TOAST = "CLEAR_REGISTER_TOAST ";

// sign in
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const CLEAR_LOGIN_TOAST = "CLEAR_LOGIN_TOAST ";
export const LOGOUT = "LOGOUT";

// wocman dashboard workdone
export const WORKDONE_PENDING = "WORKDONE_PENDING";
export const WORKDONE_SUCCESS = "WORKDONE_SUCCESS";
export const WORKDONE_FAIL = "WORKDONE_FAIL";
export const CLEAR_WORKDONE_TOAST = "CLEAR_WORKDONE_TOAST";

// wocman dashboard ratings
export const RATINGS_PENDING = "RATINGS_PENDING";
export const RATINGS_SUCCESS = "RATINGS_SUCCESS";
export const RATINGS_FAIL = "RATINGS_FAIL";
export const CLEAR_RATINGS_TOAST = "CLEAR_RATINGS_TOAST";

// wocman dashboard-completed
export const COMPLETED_PENDING = "COMPLETED_PENDING";
export const COMPLETED_SUCCESS = "COMPLETED_SUCCESS";
export const COMPLETED_FAIL = "COMPLETED_FAIL";
export const CLEAR_COMPLETED_TOAST = "CLEAR_COMPLETED_TOAST";

// wocman dashboard-wallet
export const WALLET_PENDING = "WALLET_PENDING";
export const WALLET_SUCCESS = "WALLET_SUCCESS";
export const WALLET_FAIL = "WALLET_FAIL";
export const CLEAR_WALLET_TOAST = "CLEAR_WALLET_TOAST";
